# Site settings
title: The main title of your site
description: description of the site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: pretty

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM

# Build Settings
exclude:
  - package.json
  - README.md
  - CNAME
  - public/sass
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE

# Sass Settings
sass:
  add_charset: true
  sass_dir: styles
  style: :compressed

# Contact & Social Details
email: general email of the site
tel: (+220) 444 - 5555
phone: (+220) 227 7552
address: P.O.Box 2397, Serrekunda, The Gambia

fb: #
tw: #
ig: #
yt: #
li: #

mail: https://s217085.gridserver.com/.tools/webmail/

# Analystics
gtag: UA-165092230-1

# Plugin Settings
plugins:
  #- jekyll-feed
  #- jekyll-sitemap
# Data variables
